### ISSUE TITLE
Gui Modification

### ISSUE THREAD

**Issue by RicardoThanos** [S-B99/KAMI#116] opened 2019-11-23 23:14 UTC
You should be able to resize/modify the GUI because sometimes just pressing Y will cover your entire screen and even some categories go offscreen

Make the GUI resizable by a modules/option button or something like that

I have tried putting the all the categories near eachother to makes space but that just fucks it up

**Comment by S-B99** [comment] 2019-11-23 23:14
Duplicate of #68

**Comment by S-B99** [comment] 2019-11-23 23:15
Change your Minecraft GUI size to smaller for now

**Closed** 2019-11-23 23:14 UTC
Labels: duplicate
