### ISSUE TITLE
Drag Settings boxes in clickgui

### ISSUE THREAD

**Issue by d1gress** [S-B99/KAMI#201] opened 2019-12-02 13:36 UTC
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
be able to drag settings boxes

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by S-B99** [comment] 2019-12-02 13:36
But why

**Comment by d1gress** [comment] 2019-12-02 13:37
example if a module is at the bottom of the screen then i cant change settings

**Comment by S-B99** [comment] 2019-12-02 13:37
I'm pretty sure it moves the box up to fit

**Comment by S-B99** [comment] 2019-12-02 13:37
If not just drag your entire box up

**Comment by d1gress** [comment] 2019-12-02 13:38
if its meant to then it breaks on large

**Comment by d1gress** [comment] 2019-12-02 13:38
i cant drag it are you supposed to be able to

**Comment by S-B99** [comment] 2019-12-02 13:38
You can't drag the settings but you can drag the entire category

**Comment by d1gress** [comment] 2019-12-02 13:39
small screen problems

**Comment by S-B99** [comment] 2019-12-02 13:39
Then it's a duplicate of #68 and #99

**Closed** 2019-12-02 13:39 UTC
Labels: duplicate, enhancement
