### ISSUE TITLE
Alpine doesnt work for some people like me

### ISSUE THREAD

**Issue by Vonr** [S-B99/KAMI#290] opened 2019-12-16 01:04 UTC
**Describe the bug**
Alpine does not read packets for certain people such as me.

**To Reproduce**
1. Use alpine
2. Doesnt work

**Expected behavior**
Alpine should work duh

**Screenshots**

**Additional context**
Alpine listener does jackshit and cant read packets.

**Comment by Vonr** [comment] 2019-12-16 01:05
maybe it has to do with having wireshark on my computer but highly unlikely

**Comment by S-B99** [comment] 2019-12-16 01:06
duplicate of #268

**Closed by S-B99** 2019-12-16 01:06 UTC
Labels: bug
