### ISSUE TITLE
AutoWeb/WebTrap

### ISSUE THREAD

**Issue by DontEatOreo** [S-B99/KAMI#205] opened 2019-12-02 17:42 UTC
Similar to AutoTrap it coves the player in Web.

Most useful after the player is already trapped with obsidian.

This could be used when a player is trapped to make it harder for them to escape if they don't have anything for escaping.

**Comment by S-B99** [comment] 2019-12-02 18:07
Duplicate of #132

**Closed** 2019-12-02 18:07 UTC
Labels: duplicate, new-feature
