### ISSUE TITLE
color picker for holeesp

### ISSUE THREAD

**Issue by decendium** [S-B99/KAMI#114] opened 2019-11-23 18:52 UTC
make a color wheel if you right click on HoleEsp where you can choose any RGB color and maybe if you want different colors for bedrock and obsidian have 2 different color wheels to choose colors for each one

**Comment by S-B99** [comment] 2019-11-23 18:53
Duplicate of #106 and pull #113

**Comment by S-B99** [comment] 2019-11-23 18:53
I'll close when 113 is done

**Comment by S-B99** [comment] 2019-11-30 03:30
closed in commit 058e9b49826a81cbc8fbfd925c2972ae6a779a45

**Closed** 2019-11-30 03:31 UTC
Labels: enhancement
