### ISSUE TITLE
gradle not here

### ISSUE THREAD

**Issue by d1gress** [S-B99/KAMI#269] opened 2019-12-08 13:05 UTC
**Describe the bug**
gradle not here

**To Reproduce**
1. Go to repo
2. observe gradle not being here

**Expected behavior**
gradle here

**Additional context**
gradle need

**Comment by S-B99** [comment] 2019-12-08 13:09
Duplicate of #192

**Closed by S-B99** 2019-12-08 13:09 UTC
Labels: bug

**Comment by blockparole** [comment] 2019-12-08 15:27
just use https://github.com/blockparole/KAMI-Green :P

**Comment by cookiedragon234** [comment] 2019-12-08 17:46
^

**Comment by Vonr** [comment] 2019-12-09 01:03
how about no
